### ISSUE TITLE
SMW Special pages not created

### ISSUE THREAD

**Issue by NicolasNallet** [SemanticMediaWiki/SemanticMediaWiki#1686]
### Setup and configuration
- SMW version: 2.4.0-rc1 (c4023c0) (same behaviour with 2.3.1)
- MW version: 1.26.2
- DB (MySQL etc.): MySQL    5.5.49-0ubuntu0.14.04.1
### Issue

Special page usually created by SMW (Properties, UnusedProperties, SemanticStatistics, SMWAdmin. Browse Ask, SearchByProperty) are never created.

The wiki that has this bug is private and I didnt achieve to reproduce this bug on another wiki.

**Comment by jongfeli** [comment]
Is the **Extension:ConfirmEdit** enabled on your site? If so check **[this](http://wikimedia.7.x6.nabble.com/Installed-SMW-but-no-special-pages-td5064648.html)**.

**Comment by NicolasNallet** [comment]
Indeed ConfirmEdit was enabled, and when I disabled it, SMW's Special pages are coming back.
Thank a lot !

**Comment by mwjames** [comment]
Same as #1406 and [0] has a note about this but I'm bit baffled here since [1] is running with "ConfirmEdit 1.4.0 (dbff612) 20:20, 10 June 2016" installed and shows no issues on the `Special:SpecialPages`.

As I noted before #1406, it would be great if someone could find the reason for this erratic behaviour.

[0] https://www.semantic-mediawiki.org/wiki/Help:Installation#General_notes
[1] http://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Version

**Comment by kghbln** [comment]
If just gotten around to verify this behaviour. @jongfeli Thank you for your e-mail about this! With
* MediaWiki 	1.26.3 (fa11b59) 21:41, 20. Mai 2016
* PHP 	5.4.45-0+deb7u3 (apache2handler)
* Semantic MediaWiki	2.4-alpha (f26bc07) 09:24, 30. Apr. 2016
* ConfirmEdit 1.4.0 (d36751a) 22:58, 31. Okt. 2015

it is not working either. So as soon as I pull ConfirmEdit everything is ok and I see the special pages.

**Comment by kghbln** [comment]
Just updated to Semantic MediaWiki	2.4.0-rc1 (f26bc07) without change of results. Just invoking ConfirmEdit without adding a module like e.g. QuestyCAPTCHA already causes this and it does not matter if I invoke via extension.json or via require.

**Comment by kghbln** [comment]
> Same as #1406 

Affirmative. This is a dupe. Since however this one already has more activity...

**Comment by jongfeli** [comment]
Well I completely missed #1406 so all the thank you's should go to @stefahn :smile:

**Comment by kghbln** [comment]
I guess [T138068](https://phabricator.wikimedia.org/T138068) is identical. So adding here for cross-reference.

**Comment by kghbln** [comment]
Resolved with SMW 2.4.0 according to [this post](https://phabricator.wikimedia.org/T138068#2499143).

**Comment by m-art-in** [comment]
It's still an issue in SMW 2.4.1

**Comment by kghbln** [comment]
You are on MW 1.27? If not upgrading should get you out of this issue.

**Comment by m-art-in** [comment]
Sorry, I forgot to mention:

MediaWiki 	1.27.1
PHP 	7.0.7 (apache2handler)
PostgreSQL 	9.4.9
SMW: 2.4.1

So it's still an issue for me. I disable ConfirmEdit for a while and then it's ok.....

**Comment by kghbln** [comment]
> So it's still an issue for me. 

Good to know since one can only guess. I wonder why this works on sandbox. The only difference is the PHP version, leaving the database aside.

**Comment by kghbln** [comment]
I have just upgraded from MW 1.26.4 etc. to 

- MediaWiki 	1.27.1 (4804ae5) 10. Nov. 2016, 18:11
- PHP 	5.6.26-0+deb8u1 (apache2handler)
- MySQL 	5.5.52-0+deb8u1
- Semantic MediaWiki	2.4.1 (af78257) 12. Jul. 2016, 12:28
- ConfirmEdit	1.4.0 (92652aa) 31. Aug. 2016, 10:33

and now the issue is gone. Thus closing.

**Comment by gesinn-it** [comment]
This (SMW special pages not shown) is still an issue with:

* MW 1.27.1
* PHP 7.0.8
* SMW 2.4.4
* ConfirmEdit 1.4.0

I'll have a look into ConfirmEdit and try to understand what's going on...

Here are my ConfirmEdit settings:

```
wfLoadExtension( "ConfirmEdit" );
wfLoadExtension( "ConfirmEdit/QuestyCaptcha" );
$wgCaptchaClass = "QuestyCaptcha";
$wgCaptchaQuestions[] = array( "question" => "question", "answer" => "answer");
```

**Comment by gesinn-it** [comment]
ah, okay, it's working with

latest ConfirmEdit 1.4.1 (eea2497)

**Comment by kghbln** [comment]
> ah, okay, it's working with

I am using REL1_27 ( 1.4.0 (92652aa)) on the 1.27 branch and do not have the issue either. Thanks for confirming.
