### ISSUE TITLE
Property "is locked to prevent accidental data modification while a change propagation update is run" even though no change propagation is pending

### ISSUE THREAD

**Issue by Dinoguy1000** [SemanticMediaWiki/SemanticMediaWiki#4344]
### Setup and configuration

- SMW version: 3.0.0
- MW version: 1.31.1
- PHP version: 7.2.13-1+ubuntu16.04.1+deb.sury.org+1 (fpm-fcgi)
- DB system (MySQL, Blazegraph, etc.) and version: MariaDB 10.1.31-MariaDB-1~xenial

### Issue
A property page on our wiki (https://yugipedia.com/wiki/Property:Fuses_with) reports as being locked while a change propagation is run, in spite of no such run happening or being available. This has been the state of things at least since October 10, and possibly for much longer (the page was last edited in December 2018).

### Steps to reproduce
- Visit https://yugipedia.com/wiki/Property:Fuses_with
- Click "view source"
- Observe the notice about the page being locked

**Comment by kghbln** [comment]
Use [`$smwgChangePropagationProtection = false;`](https://www.semantic-mediawiki.org/wiki/Help:$smwgChangePropagationProtection) to get out of the situation. Perhaps the frantic editing on that page confused the software. Probably also better to use datatype Text rather than String.

**Comment by Nikerabbit** [comment]
Fyi: I'm also seeing this quite frequently with category pages on my wikis. JobQueue is empty and the message doesn't go away.

**Comment by kghbln** [comment]
> Fyi: I'm also seeing this quite frequently with category pages on my wikis. JobQueue is empty and the message doesn't go away.

Hmm, never had this since it was introduced I am using SMW rather heavily I blieve. Thus I guess that we are facing reality here... We have a way out but still: @mwjames FYI

**Comment by Dinoguy1000** [comment]
The above workaround fixed this for the page on my wiki, but I agree that a better resolution would be favorable.

**Comment by JeroenDeDauw** [comment]
@Nikerabbit I've noticed that running the SMW tests on your wiki will cause this kind of error.

**Comment by Nikerabbit** [comment]
I'm not running SMW tests on my wikis though, to my knowledge.

**Comment by JeroenDeDauw** [comment]
Maybe we're so big on testing that the tests execute in a background thread for every web request? ;)

**Comment by Dinoguy1000** [comment]
We have another page doing this now, https://yugipedia.com/wiki/Property:Stars. I accidentally left the old text (including the old `has type` declaration) in place while updating the property type, and it's been locked since. The "1 job estimated" message is bogus; the job queue is clear of SMW-related jobs.

I've tried the above suggestion of `$smwgChangePropagationProtection = false;`, as well as assigning the `smw-pageedit` right to admins (also setting `$smwgEditProtectionRight = "smw-pageedit";`), and neither allows the page to be edited.

If necessary I can create a new task for this, but felt it was similar enough to continue in this task. One thing to note is that we are now using SMW 3.1.5, if that makes any difference at all.

**Comment by kghbln** [comment]
> The "1 job estimated" message is bogus; the job queue is clear of SMW-related jobs.

You are sure that at the time the deadlock of the page occurred there was not SMW-releated job?

> I accidentally left the old text (including the old has type declaration) in place while updating the property type, and it's been locked since. The "1 job estimated" message is bogus; the job queue is clear of SMW-related jobs.

I am not sure if I have done the same however I have this issue too with one property page, i.e. there are circumstances that allow a page to be locked whatever you do.

**Comment by Dinoguy1000** [comment]
> You are sure that at the time the deadlock of the page occurred there was not SMW-releated job?

When I made the edit there were other SMW-related jobs in the queue, but not from previous modifications of that property. Since then, all SMW jobs have been done.

**Comment by kghbln** [comment]
I believe the issue here is that SMW still believes that a job is to be cleared and does not recognize what this is no longer the case. We have some kind of "artifact" job reference here and no way to clear it.

**Comment by Dinoguy1000** [comment]
Is there something I can do server-side to clear it? Or at least to gather more information for you guys to debug with?

**Comment by kghbln** [comment]
I have not found a way. Even deleting and restoring the property page does not change the situation. What I have not done is dropping the backend and get a fresh start on the property. This is overdoing things though and I am not sure if this will help either.

**Comment by Dinoguy1000** [comment]
Given the [number of annotations](https://yugipedia.com/wiki/Special:Statistics) we deal with, I don't think a complete rebuild just for this is a great idea either.

**Comment by mwjames** [comment]
Well, the lock relies on the jobqueue information about the state and deduce whether something is holding a reference to it or not. For details, see [0].

The reliance of the jobqueue as tracker is fragile and I have a different idea in mind on how to better track the state but I don't know when this is going to happen.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/Property/DeclarationExaminer/ChangePropagationExaminer.php

**Comment by Dinoguy1000** [comment]
Sometime since I reported the new page lock issue, the phantom job cleared, and now the page is just locked. The lock message mentions the `smw-pageedit` right, and [Special:ListGroupRights](https://yugipedia.com/wiki/Special:ListGroupRights#sysop) shows admins have that right, but I am still unable to edit the property. (For the sake of convenience and clarity, here's a link to the page again: https://yugipedia.com/wiki/Property:Stars.)

**Comment by mwjames** [comment]
> Sometime since I reported the new page lock issue, the phantom job cleared, and now the page is just locked. The lock message mentions the smw-pageedit right, a

But this has nothing to do with the change propagation, this is message that comes from [0] and I'm guessing someone has protected to the property manually.

As a side note:

"The property contains competing type specifications which may result in invalid value annotations therefore it is expected that a user assigns one appropriate type." defining the property as number and type, what is this?

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/Property/DeclarationExaminer/ProtectionExaminer.php

**Comment by kghbln** [comment]
I think this has nothing to do with the `smw-pageedit` permission. This is just the natural thing to look at first when trying to overcome the lockdown.

> I'm guessing someone has protected to the property manually.

The lockdown occurs even it the page was not protected from editing manually. At least in my case this is not what is causing the issue. Probably also true for Dino.

**Comment by mwjames** [comment]
> The lockdown occurs even it the page was not protected from editing manually. At least in my case this is not what happened thus not causing the issue. Probably also true for Dino.

I have to say that I'm unable to understand the issue, if the change propagation is ongoing and the property contains the a `Change propagation` property then the property is locked for said reasons (see the documentation for details). If the the `Change propagation` property is removed (means the dispatch job was able to find a related subjects) then the lock caused by `Change propagation` is lifted.

**Comment by kghbln** [comment]
The issue boils down to that we have a property page that was not protected manually with no propagation job left since the last edit that cannot be edited manually, no matter what.

**Comment by mwjames** [comment]
As I said, the message your seeing is from [0] which has nothing to do with the change propagation and is being shown because the `smw-pageedit` permission is expected. The relevant code to check for the permission is in [1]. As of now, I unable to verify the issue on my local wiki so unless someone tells me a reliable way to replicate to issue, don't expect further comments from my side.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/Property/DeclarationExaminer/ProtectionExaminer.php

[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/3.1.x/src/MediaWiki/PermissionManager.php#L145-L204

**Comment by Dinoguy1000** [comment]
> But this has nothing to do with the change propagation, this is message that comes from [0] and I'm guessing someone has protected to the property manually.
No one's touched the protection level of the property, as can be seen from its [edit history](https://yugipedia.com/wiki/Property:Stars?action=history) and [logs](https://yugipedia.com/index.php?title=Special:Log&page=Property%3AStars).

> As a side note:
> 
> "The property contains competing type specifications which may result in invalid value annotations therefore it is expected that a user assigns one appropriate type." defining the property as number and type, what is this?
The issue that led to this happening in the first place. I was updating the property using a copy-paste of its then-current text (well, actually a copy of the updated text of a closely-related property), and forgot to delete the old text before saving.

> I have to say that I'm unable to understand the issue, if the change propagation is ongoing and the property contains the a `Change propagation` property then the property is locked for said reasons (see the documentation for details). If the the `Change propagation` property is removed (means the dispatch job was able to find a related subjects) then the lock caused by `Change propagation` is lifted.
There is no change propagation running for this or any other property; they all already finished. There is also no `Change propagation` property in the text of this property (I'm guessing that's what you're talking about). If the `Change propagation` property applies without being in the text of a property, and there's a way to manually remove it, I'd love to know.

> Try to edit page using the ReplaceText extension. I now remember that I was able to edit my property page this way.
I'll give it a shot, thanks for the pointer. =)

> As I said, the message your seeing is from [0] which has nothing to do with the change propagation and is being shown because the `smw-pageedit` permission is expected.
As I showed with my link to our S:ListGroupRights page, admins have `smw-pageedit` assigned (and I am an admin on the wiki); this was one of the things I tried to fix this issue before reporting it here.

> As of now, I unable to verify the issue on my local wiki so unless someone tells me a reliable way to replicate to issue, don't expect further comments from my side.
The only thing I can suggest to attempt replication is to set up a test wiki with some relatively widely-used property (if you don't have such a wiki handy already) and add a new `has type` declaration to the property that changes its type, without replacing or removing the first one. This is the only time I've experienced this particular problem, and that is the condition that seems most obvious about it to me.

If you still can't replicate it (or if that's what you tried when you attempted replication) then it's perfectly reasonable that you wouldn't comment here more, if you have nothing else to add. Sometimes you just run out of things to say. =X

**Comment by Dinoguy1000** [comment]
> Edit: @Dinoguy1000 Try to edit page using the ReplaceText extension. I now remember that I was able to edit my property page this way.

It worked! Thanks a ton for the suggestion. =D

Now to see if this turns out to be enough to also clear the protection...

**Comment by kghbln** [comment]
> Now to see if this turns out to be enough to also clear the protection...

Actually it was. I was able to edit the page as an IP. I'd prevent this.

**Comment by Dinoguy1000** [comment]
> I was able to edit the page as an IP. I'd prevent this.

Is this a general suggestion for all property pages? Is there a page on the SMW wiki which advises best practices for SMW-related page permissions?

**Comment by verdy-p** [comment]
> Fyi: I'm also seeing this quite frequently with category pages on my wikis. JobQueue is empty and the message doesn't go away.

Yes, this happens repeatedly in translatewiki.net. Even after a page (a category page) was just created once, and never edited later, it was locked permanently since the first creation time). And there's no way to reedit it later to change some bits.

**Comment by kghbln** [comment]
Thanks a lot for reporting our experience and ideas about this. Ever since I set [`$smwgChangePropagationProtection = false;`](https://www.semantic-mediawiki.org/wiki/Help:$smwgChangePropagationProtection) this did no longer happen to me though I cannot tell if I just was lucky. Probably one should only do this on a non-publicly editable wiki or a wiki with lower likelyhood that wrong doing can occur.

What happened to me once was that I edited on a page while heaps of change propagation jobs were open for another page. This triggered a lockdown.

> now we cannot 

use the ReplaceText extension to edit these pages. I cannot test on twn since I can no longer use the extension.

**Comment by verdy-p** [comment]
> Thanks a lot for reporting our experience and ideas about this. Ever since I set [`$smwgChangePropagationProtection = false;`](https://www.semantic-mediawiki.org/wiki/Help:$smwgChangePropagationProtection) this did no longer happen to me though I cannot tell if I just was lucky. Probably one should only do this on a non-publicly editable wiki or a wiki with lower likelyhood that wrong doing can occur.
> 
> What happened to me once or twice was that I edited on a page while heaps of change propagation jobs were still open for another page. This triggered a lockdown for the edited page.
> 
> > now we cannot
> 
> Use the ReplaceText extension to edit these pages. I cannot test on twn since I can no longer use the extension.

There's no such extension in Translatewiki.net. I think this can only be solved for now by an SQL admin, removing the locked status manually in the SQL database, or running some admin maintenance script to check and cleanup the incorrect locked status after check the locked page is not referenced by any pending job.

I don't know if SemanticWiki provides such maintenance script for wiki admins.

**Comment by kghbln** [comment]
> There's no such extension in Translatewiki.net

Sure there is. However you have to be translation administrator to use it: https://translatewiki.net/wiki/Special:ReplaceText

> I don't know if Semantic MediaWiki provides such maintenance script for wiki admins.

No and this appears just to help fixing the result of an issue rather that the issue itself.

**Comment by verdy-p** [comment]
> > There's no such extension in Translatewiki.net
> Sure there is. However you have to be translation administrator to use it: https://translatewiki.net/wiki/Special:ReplaceText

So I cannot use it...

> > I don't know if Semantic MediaWiki provides such maintenance script for wiki admins.
> No and this appears just to help fixing the result of an issue rather that the issue itself.

Standard Mediawiki provides a lot of such maintenance script (notably for recovery after some server crash, or for version checking and upgrading some status/tables when a new database schema is published, or for reindexing tables with new collation data for a newer Unicode version or a new CLDR dataset, or for various extensions.

Many of these maintenance scripts can run in the administrator's wiki console from their web browsers, where they can be launched without logging directly on the server with a *nix  command line shell via SSH.

**Comment by kghbln** [comment]
> Is this a general suggestion for all property pages? Is there a page on the SMW wiki which advises best practices for SMW-related page permissions?

@Dinoguy1000 I must have overlooked you post. I just added a [note](https://www.semantic-mediawiki.org/w/index.php?title=Help%3AProperty_page&type=revision&diff=77444&oldid=74032) to the respective page.

**Comment by verdy-p** [comment]
> I just added a [recommendation](https://www.semantic-mediawiki.org/w/index.php?title=Help%3AProperty_page&type=revision&diff=77445&oldid=74032) to the respective page.

This does not apply to the bug seen translatewiki.net: there was no change in datatypes, only the initial creation of a new very basic page with a category, and while the server had very low activity (no job pending initaiolly when the pages were submitted, this is easy to see in the wiki history log).

The only "maintenance" task was for the "changes" in categories, when it fact there was no change at all, it was an addition of a *new* page into an existing category (something that does not require any privilege and is a basic action performed by any user editing any page).

If you look at the (public) wiki history log you'll see that the "locked" page was created at approximately the same time as another page created by the same or another user, not seeing any "maintenance" warning at top before submitting his creation. Such condition is then completely unpredictable and can happen at any time. There was no abuse at alls of any privilege, no stress at all on the server it is only bound to very short period of times where two actions may occur simultaneously on a non-busy/idle server.

**Comment by kghbln** [comment]
@verdy-p I am on the brink of locking this thread. Of course this does not apply to what you wrote. This is an answer to @Dinoguy1000 and not to you.

**Comment by DSwissK** [comment]
Had the same problem with 2 attributes on my website.

Just confirming that using ReplaceText works fine : https://dicoado.org/wiki/index.php?title=Attribut%3ALien&type=revision&diff=49842&oldid=49789

**Comment by Rififia** [comment]
I've managed to clear the error on dicoado, the site of Dsissk above, by purging the cache. I've just ran update.php, it purged the cache, and done.

**Comment by verdy-p** [comment]
No progress for now:

Still this page is incorrectly "''is locked to prevent accidental data modification while a change propagation update is run''" even though no change propagation is pending since its initial creation (never edited since then):

https://translatewiki.net/wiki/Category:Salishan_languages (already signaled above 23 days ago, but locked since 22 Jun, nearly 6 weeks ago)

It makes no sense at all, and SemanticMediaWiki really needs to develop a cleanup tool that site admins can run more simply, without having to search for specific locked pages that Semantic Mediawiki kept without creating any job to remove these page from the queue. This is definitely a bug of Semantic Mediawiki when it attempts to create a job (which is never commited or throws an error (may be because of concurrent queries on the DB, such as when creating temporary tables: the SQL schema should not be modified like this, it should be serialized but not made within the concurrent page parsing/rendering threads, and the separated serialization should use its own independant transactions, only for jobs in the job queue, but never for page editing/rendering).

**Comment by verdy-p** [comment]
I found a way to get a list of the affected page. In fact this is caused by the special property "Change propagation" being added to the affected pages (all of them categories) but never removed.

In fact this property is added AFTER the background job has already run and finished its job (this job did not find any property to delete, it silently terminated itself).

See this report on Translatewiki.net (various are caused by my own basic edits of pages to add/remove/change a category, some occurs immediately after creating a new category with a single edit. Some are caused by other users doing the same thing.
So this affects wikis whose job queue is empty when an edited page is saved to add/change/remove any categorization.

```
https://translatewiki.net/w/i.php?title=Special:Ask&q=%5B%5BChange+propagation%3A%3A%2B%5D%5D&p=format%3Dbroadtable%2Flink%3Dall%2Fheaders%3Dshow%2Fsearchlabel%3D...-20further-20results%2Fclass%3Dsortable-20wikitable-20smwtable%2Fsep%3D%2C-20&sort=&order=asc&eq=no&offset=0&limit=50
```

or just:

```
{{#ask:[[Change propagation::+]]}}
```
None of these pages have any job pending. They are locked since very long (more than one year for some).

And I don't see how we can remove these spurious special properties (which are not auditable with the common special pages, without knowing the internal special properties (that are hard to find, as the helpers in Special:Ask do not propose them and there's no simple report listing the defined special properties in the default installation Semantic Mediawiki; such hidden "magic" should never occur; it must be better documented; all we can see is the SQL report for debugging which just displays the internal SQL table names and some cryptic fields that no wiki admin can reasonable guess or manage without being himself a SMW developer and knowing perfectly the internal complex schema used, and poorly documented)

**Comment by verdy-p** [comment]
See also https://translatewiki.net/wiki/Translating:Localisation_for_developers#Unexpectedly_locked_pages
NOTHING has changed with your fix, you did not not fix anything. And the bug continues with some pages added randomly to the list of locked page.

This is definitely a race condition between the time the jobn is setup in one thread (but the status is kept in a cache that will be stored later) and the background job that can run and terminate earlier, trying to delete the ```[[Change propagation::+]]```` pseudo-property for this page from the database '''before''' the status (kept in a  cache of the main process) was actually commited to the database by the main thread. It seems to occur because the main thread may want to service other incoming requests from other visitors of the website.

**Comment by verdy-p** [comment]
I've found a workaround that works for some pages:
On those pages that don't have an "Edit" tab but a "View source" tab,
* click on it: this opens the editor in readonly mode.
* change end of the URL from "action=edit" to "action=purge", validatate
* click to confirm the purge, if you are requested.
* This displays the page again still with the "View source" tab, but if you click it again immediately, the editor ''may'' finally run in normal edit mode. Save the page as is (i.e. make a null edit without changing anything, notably not any referenced category)
* Now the page is unlocked. The trick is to force the purge and edit it fast enough before the cache is refilled with an edit-lock.

This does not work on all pages (apparently this occurs when there are two (duplicated) locking properties in SemanticWiki for the same page (the Mediawiki "purge cache" only removes the first one, the second one is kept, and it still locks the page and the special property will be added again as a duplicate; most probably this duplicate property has another internal difference in some of its tags, probably an old one)

This also does not work to fix the lock on page that cause a reference loop (e.g. a hard redirect of categories to any other one or to itself because of a mistake while editing the page, or saving it too soon before changing the redirect, e.g. by pressing the TAB key by error and pressing Enter to save it, and there's no prompt to confirm the save as there was an edit comment and no other warning detected about such reference loops).

Now there remains the main bug of locks left permanently on category redirects (hard redirects with `#REDIRECT [[]]` to any other page in any namespace) or to the current page itself. Such mistakes are possible and generally made unvoluntarily, but can't be corrected by the user seeing that.

This can occur at any time, from any user (confirmed or not), and can cause a nightmare on wikis as it allows some form of denial of service attacks that will require a site admin to fix it, as such edits (made unvoluntarily, or not) can't be easily reverted and important pages (or templates, modules) could be blanked and locked and generate lot of problems on the wiki if this affects a widely referenced page: being a simle translation admin, or wiki admin, or reviewer is not enough, this can only be solved by a site admin with a manual update in the database (using the SQL console with full access to the database, so this fix can't be open to "normal" wiki admins.

The SQL access privilege often requires access on a system shell console, and can expose data protected by privacy, so only site owners: very few "super-admins" (or just a single one in "small" sites) that can install Mediawiki on their own hosting server can do that; such correction using direct SQL can also be quite dangerous, the SQL request could delete many things, leaving nothing in the wiki history, and if there's any error, the site admin will have to restore the database from a backup dump, loosing all recent edits made after this last database dump; restoration will also require putting the whole site in read-only mode, for long time if there's the need to reload tens or hundreds of gibabytes). For this reason, a correction script should be created for such maintenance, to perform checks and avoid damaging or dangerous errors, and to avoid direct access to private user data (which should remain secret).

**Comment by Seb35** [comment]
I observed this issue on a newly-installed MW 1.36 + SMW 4.0.0-alpha and investigated, and have a reasonably-plausible hypothesis involving the cache in `ChangePropagationDispatchJob`.

**Summary**

The short answer is: **whether you experience or not this issue depends on your $smwgMainCacheType**:
* memcached, Redis, DB are immune;
* APCu has the issue.

**Details**

*The theory is:* ChangePropagationDispatchJob caches for 24h the number of jobs related to the given page, then when the jobs are executed the cache key for this page is deleted.

*A focus about the cache type:* it is a composite cache composed of Onoi\Cache\FixedInMemoryLruCache and a MW cache fixed by `$smwgMainCacheType` (and if the default CACHE_ANYTHING is used, depending on `$wgMainCacheType` or other cache parameters, see ObjectCache::newAnything for the exact logic). When a value is written in this composite cache, it is written on all sub-caches. When a value is fetch from this composite cache, the first value existing in a cache is returned. The first sub-cache FixedInMemoryLruCache is not significant here because it is very short term (discarded at the end of the request).

*The core issue:* In the case where the SMW main cache is shared between Web and CLI (memcached, Redis, DB) there is no issue because, when the job is executed in CLI, the cached value is deleted in the SMW main cache and the Web can access this state (deleted cached value); but if the SMW main cache is not shared between Web and CLI, the cached value is initially saved in the Web-accessible cache, and deleted (by the job) in the CLI-accessible cache, and in this case remaining in the Web-accessible cache.

----

Appendix: the actions which leads me into this hypothesis:
1. on my test MW 1.36, the MW installer set up `$wgMainCacheType = CACHE_ACCEL;` (APCu in-process cache)
2. I created a page property, setting its type and got a `Change propagation updates are pending (3 jobs estimated)` warning
3. I ran `php maintenance/runJobs.php`
4. The warning on the page was still present
5. I changed `$wgMainCacheType = CACHE_DB;` : the warning on the page was removed
6. I changed back to `$wgMainCacheType = CACHE_ACCEL;` : the warning came back
7. By exploring with `php maintenance/eval.php`:
```php
> $applicationFactory = SMW\ApplicationFactory::getInstance();
> $subject = new SMW\DIWikiPage( 'Prop1', 102 );
> var_dump( SMW\MediaWiki\Jobs\ChangePropagationDispatchJob::hasPendingJobs( $subject ) );
0
```
8. I added the following code at the end of ChangePropagationDispatchJob::hasPendingJobs just before the return:
```php
var_dump( $applicationFactory->getCache()->getName() );
var_dump( $applicationFactory->getCache()->fetch( $key ) );
```
* in CLI it is displayed
```
string(100) "Onoi\Cache\CompositeCache::Onoi\Cache\FixedInMemoryLruCache::Onoi\Cache\MediaWikiCache::SqlBagOStuff"
bool(false)
```
* in Web it is displayed
```
string(100) "Onoi\Cache\CompositeCache::Onoi\Cache\FixedInMemoryLruCache::Onoi\Cache\MediaWikiCache::APCUBagOStuff"
int(3)
```
(it can be noted that the CLI cache is SQL even if `$wgMainCacheType = CACHE_ACCEL;`, this is because `ObjectCache::makeLocalServerCache()` prevents using APCu in CLI, but even if it would authorise it, the corresponding cache would be discarded at the end of the CLI execution and not shared with the Web anyway.)

**Comment by PaulWieland** [comment]
Experiencing the same exact issue described here. Through debugging I determined that for some reason the protection value of the property page is cached, and the cache never seems to get updated.

As a temporary fix, I commented out this line: https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/91546f4c02af0409f97bacecd142a6170d78cde2/src/Protection/ProtectionValidator.php#L332

This skips the cache reading for the `checkProtection` method.

**Comment by verdy-p** [comment]
Note that one TranslateWiki.net, the work around is tracked on this page:

> https://translatewiki.net/wiki/Thread:Translating_talk:Localisation_for_developers/Unexpected_permanently_locked_pages_(bug_occuring_randomly,_caused_by_SemanticMediawiki_for_its_%22change_propagation%22)

It gives a workaround: you may need to force the refresh of the page. A common solution is to enable (in your users preferences) the gadget that displays an UTC clock at top of page; clicking on it causes that page to be parsed again; reload that page after the click to see if the page is still locked (it may still take some time, about 1 minute or so for the actual refresh being made). If this still does not work, try it on the next day.

That tracking page performs a query to Semantic Mediawiki to get the list of affected pages.

However this work around does not solve the problem caused by some redirects (e.g. from a page to itself), which will remain permanently locked (when in fact the "#REDIRECT" link in the content should be removed, or replaced by another target link (but this cannot be done as long as the page is locked, except by a site admin using a forced edit before doing a forced refresh of the page to remove that lock.

**Comment by krabina** [comment]
> I've found a workaround that works for some pages: On those pages that don't have an "Edit" tab but a "View source" tab,
> 
Thank you for this workaround. I experienced this issue on category pages and could solve it with this trick. 
The environment:
<html><body>


MediaWiki | 1.31.14
-- | --
PHP | 7.2.24 (fpm-fcgi)
MySQL | 5.5.62-log
ICU | 50.1.2
Semantic MediaWiki | 3.1.6

["smwgMainCacheType"](javascript:;):  -1,
["smwgQueryResultCacheType"](javascript:;): 0,
["smwgQueryResultCacheLifetime"](javascript:;): 604800,
["smwgQueryResultNonEmbeddedCacheLifetime"](javascript:;): 600,
["smwgQueryResultCacheRefreshOnPurge"](javascript:;): true,

**Comment by verdy-p** [comment]
I still don't understand the interest of keeping the "accelerated cache" (with APCu enabled) on the web, when the web otself will create jobs that will run later in the CLI and that will not use that cache but the SQL cache. There's no way to synchronize these different caches, so background jobs will never be able to mark the "accelerated cache" as being now dirty when these CLI jobs finish their jobs and correctly update the DB. So the web will always ermain out of sync, until its "accelerated cache" gets flushed. In my opinion the persistance of the "accelerated cache" (APCu) is MUCH too long, and its content should never remain in memory for more than 2 minutes. The "accelerated cache" should then invalidate rapidly all its entries, and will have to be refilled by issuing a new real SQL request (and there this can pass through the normal cache... which is shared across all processes includnig the CLI adn can have a long persistance in time: so even if the web still does not refresh the pages correctly, at least by refreshing the page normally after a couple of minutes, these issues would disappear.
But the "accelerated cache" offers in fact no benefit: we can use good external caches (like "memcache") notably if it runs on the same machine as the web server, or is reachable via a fast local network, and we won't notice any difference of performance even if we have APCu disabled or just the "accelerated cache", which is always unsafe (and does not scale on webservers running on multiple hosts with a load balancer). The same is true for other kind of caches (e.g. Squid for web requests, or filesystem caches for remotely mounted shared volumes, or SQL client caches): they all offer cache synchronization mechanisms (that the "APCu accelerated cache" still does not have, because it was not designed to support concurency on parallel computing units; today all modern machines use hardware-level parallelism, and this trend will continue to grow dramatically, because working frequencies for individual processing units have reached a plateau; we do need and can only safely used caches that offer a synchronization interface with concurrent processing units, we cannot count on basic memory-only caches that are not offering any service for synchronization with external devices).

As long as the "APCu accelerated cache" does not offer and support such synchronization service with external processes or devices, possibly running in other CPUs or remote hosts, it cannot be transted and used (except on very small wiki servers), and the best alternative to it is "memcached" (or similar modern caches really designed for multiprocessing), so for now it should be stringly marked as "deprecated" and "not recommended (at least as long as it is not fixed with the needed service and there's some additional adapters to that supplementary service, which can be used by the webserver and by concurrent CLI processes possibly not all necessarily running on the same host, so that sync service should also be reachable with a RPC network API, not just by local IPC request depending entirely on shared memory)!

**Comment by krabina** [comment]
Not to get your hopes up too high, I am experiencing this issue also in a wiki with all caching disabled. (Only in one though, others do not show the problem.)

**Comment by Dinoguy1000** [comment]
We're now experiencing a similar issue with recently-created categories instead (including at least one case of a locked category that does not display any notice).

**Comment by Nikerabbit** [comment]
In my case, the jobs were failing due to memory restriction (needs over 1G), and now they are failing due to too large SQL query:

```
2023-03-24 06:59:06 RuntimeException: Error 1153: Got a packet bigger than 'max_allowed_packet' bytes
Function: SMW\SQLStore\Lookup\DisplayTitleLookup::prefetchFromList
Query: SELECT  smw_id,smw_title,smw_namespace,smw_hash  FROM `smw_object_ids`    WHERE smw_hash IN ('e415f784a9fdfab8cc60dbca782fd3731045194f','a664f7f80c8d572b70ce64b78dee594d5df159e2','895afb55fa468074c5

#0 /data/srv/mediawiki/tags/2023-03-24_06:57:43/includes/libs/rdbms/database/Database.php(1590): Wikimedia\Rdbms\Database->getQueryException('Got a packet bi...', 1153, 'SELECT  smw_i
#1 /data/srv/mediawiki/tags/2023-03-24_06:57:43/includes/libs/rdbms/database/Database.php(1564): Wikimedia\Rdbms\Database->getQueryExceptionAndLog('Got a packet bi...', 1153, 'SELECT
#2 /data/srv/mediawiki/tags/2023-03-24_06:57:43/includes/libs/rdbms/database/Database.php(1173): Wikimedia\Rdbms\Database->reportQueryError('Got a packet bi...', 1153, 'SELECT  smw_id
#3 /data/srv/mediawiki/tags/2023-03-24_06:57:43/includes/libs/rdbms/database/Database.php(1813): Wikimedia\Rdbms\Database->query('SELECT  smw_id,...', 'SMW\\SQLStore\\Lo...', 32)
#4 /data/srv/mediawiki/tags/2023-03-24_06:57:43/includes/libs/rdbms/database/DBConnRef.php(69): Wikimedia\Rdbms\Database->select('smw_object_ids', Array, Array, 'SMW\\SQLStore\\Lo...'
#5 /data/srv/mediawiki/tags/2023-03-24_06:57:43/includes/libs/rdbms/database/DBConnRef.php(320): Wikimedia\Rdbms\DBConnRef->__call('select', Array)
#6 /data/srv/mediawiki/tags/2023-03-24_06:57:43/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(246): Wikimedia\Rdbms\DBConnRef->select('smw_object_ids', Array, Arr
#7 /data/srv/mediawiki/tags/2023-03-24_06:57:43/extensions/SemanticMediaWiki/src/SQLStore/Lookup/DisplayTitleLookup.php(64): SMW\MediaWiki\Connection\Database->select('smw_object_ids'
#8 /data/srv/mediawiki/tags/2023-03-24_06:57:43/extensions/SemanticMediaWiki/src/DisplayTitleFinder.php(158): SMW\SQLStore\Lookup\DisplayTitleLookup->prefetchFromList(Array)
#9 /data/srv/mediawiki/tags/2023-03-24_06:57:43/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/CacheWarmer.php(134): SMW\DisplayTitleFinder->prefetchFromList(Object(SMW\Iterato
#10 /data/srv/mediawiki/tags/2023-03-24_06:57:43/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/EntityIdManager.php(973): SMW\SQLStore\EntityStore\CacheWarmer->prepareCache(Obj
#11 /data/srv/mediawiki/tags/2023-03-24_06:57:43/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/EntityLookup.php(402): SMW\SQLStore\EntityStore\EntityIdManager->warmUpCache(Obj
#12 /data/srv/mediawiki/tags/2023-03-24_06:57:43/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/EntityLookup.php(415): SMW\SQLStore\EntityStore\EntityLookup->getPropertySubject
#13 /data/srv/mediawiki/tags/2023-03-24_06:57:43/extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(273): SMW\SQLStore\EntityStore\EntityLookup->getAllPropertySubjects(Object(SMW\
#14 /data/srv/mediawiki/tags/2023-03-24_06:57:43/extensions/SemanticMediaWiki/src/SQLStore/Lookup/ChangePropagationEntityLookup.php(89): SMW\SQLStore\SQLStore->getAllPropertySubjects(
#15 /data/srv/mediawiki/tags/2023-03-24_06:57:43/extensions/SemanticMediaWiki/src/SQLStore/Lookup/ChangePropagationEntityLookup.php(68): SMW\SQLStore\Lookup\ChangePropagationEntityLoo
#16 /data/srv/mediawiki/tags/2023-03-24_06:57:43/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/ChangePropagationDispatchJob.php(244): SMW\SQLStore\Lookup\ChangePropagationEntityLook
#17 /data/srv/mediawiki/tags/2023-03-24_06:57:43/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/ChangePropagationDispatchJob.php(206): SMW\MediaWiki\Jobs\ChangePropagationDispatchJob
#18 /data/srv/mediawiki/tags/2023-03-24_06:57:43/includes/jobqueue/JobRunner.php(383): SMW\MediaWiki\Jobs\ChangePropagationDispatchJob->run()
#19 /data/srv/mediawiki/tags/2023-03-24_06:57:43/includes/jobqueue/JobRunner.php(344): JobRunner->doExecuteJob(Object(SMW\MediaWiki\Jobs\ChangePropagationDispatchJob))
#20 /data/srv/mediawiki/tags/2023-03-24_06:57:43/includes/jobqueue/JobRunner.php(248): JobRunner->executeJob(Object(SMW\MediaWiki\Jobs\ChangePropagationDispatchJob))
#21 /data/srv/mediawiki/tags/2023-03-24_06:57:43/maintenance/runJobs.php(98): JobRunner->run(Array)
#22 /data/srv/mediawiki/tags/2023-03-24_06:57:43/maintenance/doMaintenance.php(114): RunJobs->execute()
#23 /data/srv/mediawiki/tags/2023-03-24_06:57:43/maintenance/runJobs.php(136): require_once('/data/srv/media...')
#24 {main}
#0 /data/srv/mediawiki/tags/2023-03-24_06:57:43/extensions/SemanticMediaWiki/src/SQLStore/Lookup/DisplayTitleLookup.php(64): SMW\MediaWiki\Connection\Database->select(string, array, a
#1 /data/srv/mediawiki/tags/2023-03-24_06:57:43/extensions/SemanticMediaWiki/src/DisplayTitleFinder.php(158): SMW\SQLStore\Lookup\DisplayTitleLookup->prefetchFromList(array)
#2 /data/srv/mediawiki/tags/2023-03-24_06:57:43/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/CacheWarmer.php(134): SMW\DisplayTitleFinder->prefetchFromList(SMW\Iterators\Mapp
#3 /data/srv/mediawiki/tags/2023-03-24_06:57:43/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/EntityIdManager.php(973): SMW\SQLStore\EntityStore\CacheWarmer->prepareCache(SMW\
#4 /data/srv/mediawiki/tags/2023-03-24_06:57:43/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/EntityLookup.php(402): SMW\SQLStore\EntityStore\EntityIdManager->warmUpCache(SMW\
#5 /data/srv/mediawiki/tags/2023-03-24_06:57:43/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/EntityLookup.php(415): SMW\SQLStore\EntityStore\EntityLookup->getPropertySubjects
#6 /data/srv/mediawiki/tags/2023-03-24_06:57:43/extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(273): SMW\SQLStore\EntityStore\EntityLookup->getAllPropertySubjects(SMW\DIProper
#7 /data/srv/mediawiki/tags/2023-03-24_06:57:43/extensions/SemanticMediaWiki/src/SQLStore/Lookup/ChangePropagationEntityLookup.php(89): SMW\SQLStore\SQLStore->getAllPropertySubjects(S
#8 /data/srv/mediawiki/tags/2023-03-24_06:57:43/extensions/SemanticMediaWiki/src/SQLStore/Lookup/ChangePropagationEntityLookup.php(68): SMW\SQLStore\Lookup\ChangePropagationEntityLook
#9 /data/srv/mediawiki/tags/2023-03-24_06:57:43/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/ChangePropagationDispatchJob.php(244): SMW\SQLStore\Lookup\ChangePropagationEntityLooku
#10 /data/srv/mediawiki/tags/2023-03-24_06:57:43/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/ChangePropagationDispatchJob.php(206): SMW\MediaWiki\Jobs\ChangePropagationDispatchJob
#11 /data/srv/mediawiki/tags/2023-03-24_06:57:43/includes/jobqueue/JobRunner.php(383): SMW\MediaWiki\Jobs\ChangePropagationDispatchJob->run()
#12 /data/srv/mediawiki/tags/2023-03-24_06:57:43/includes/jobqueue/JobRunner.php(344): JobRunner->doExecuteJob(SMW\MediaWiki\Jobs\ChangePropagationDispatchJob)
#13 /data/srv/mediawiki/tags/2023-03-24_06:57:43/includes/jobqueue/JobRunner.php(248): JobRunner->executeJob(SMW\MediaWiki\Jobs\ChangePropagationDispatchJob)
#14 /data/srv/mediawiki/tags/2023-03-24_06:57:43/maintenance/runJobs.php(98): JobRunner->run(array)
#15 /data/srv/mediawiki/tags/2023-03-24_06:57:43/maintenance/doMaintenance.php(114): RunJobs->execute()
#16 /data/srv/mediawiki/tags/2023-03-24_06:57:43/maintenance/runJobs.php(136): require_once(string)
#17 {main}
```

The code desperately needs to learn batching, because updating a property used only on 300k pages is impossible.

**Comment by Oldiesmann** [comment]
Any updates on this? I have a property on my wiki showing this, and the only way I can edit it is to either use Special:ReplaceText or temporarily set `$smwgChangePropagationProtection` to false in LocalSettings.php. I'm the only one who can edit properties at the moment (still working on building properties and such before I officially declare the wiki "open"), but I'd like to have it work properly in the future in case I end up giving others the ability to edit properties at some point.

https://www.archiepedia.org/wiki/Property:Series
MW 1.43.1
PHP 8.4.6
SMW 5.01
DB version: 10.11.11-MariaDB-ubu2204

**Comment by D-Groenewegen** [comment]
Still there in SMW 7.2.0.

### Setup
- SMW version: 7.2.0
- MW version: 1.43.9
- PHP version: 8.2

### Issue
On a fresh new wiki with SMW 7.2.0, property pages are locked by page protection, preventing them from being edited:

```
This page is [protected] to prevent accidental data modification and can only be edited by users with the appropriate edit right ("") or user group.
```
Does the empty value printed for 'edit right' give us a clue here?

If I remember correctly, I was able to edit property pages at first and the message first appeared after a maintenance script was executed.

### What I tried
- The first time I saw the page protection message I edited my user's user groups to include 'smwadministrator', 'smwcurator' and 'smweditor', which I hadn't done before. 
- Ran `run.php update`
- Ran `run.php runJobs` to make sure there aren't any leftover jobs, such as those for any change propagation. 

The job queue is empty, but the edit protection remains in place. Like others, I was only able to get rid of it by setting `$smwgChangePropagationProtection = false;`
